ARG PHP_VERSION=5.6

FROM aprimediet/php:${PHP_VERSION}-alpine
LABEL maintainer="<Aditya Prima> aprimediet@gmail.com"

# Install nginx
RUN --mount=type=cache,target=/var/cache/apk \
    apk add --update \
    nginx openssl

# COPY CONFIGURATION FILES
ADD ./base/etc /etc
ADD ./php/etc /etc
ADD ./php/usr /usr

# CLEAN CACHE
RUN rm -vrf /var/cache/apk/*

RUN chown -R www-data:www-data /usr/www

EXPOSE 80 443
